services:
  postgres:
    image: postgres:16
    container_name: jmi_postgres
    environment:
      POSTGRES_USER: jmi_user
      POSTGRES_PASSWORD: jmi_pass
      POSTGRES_DB: job_market
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: